services:
  postgres:
    image: postgres:13.6-alpine
    environment:
      - POSTGRES_USER=viet
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./db_pg:/var/lib/postgresql/data
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=mongo
    ports:
      - 27017:27017
    volumes:
      - ./db_mongo:/data/db
volumes:
  db_mongo:
  db_pg: